### ISSUE TITLE
add ciu plugin, improve js-eval and npm

### ISSUE THREAD

**Issue by caub** [brigand/jellobot#79]
- [ ] add ciu based on https://github.com/oftn-oswg/oftn-bot/blob/master/lib/caniuse/index.js
- [ ] remove trailing line-returns in js-eval output
- [ ] see if we can give link to sources (github generally) in npm plugin

**Comment by ljharb** [comment]
@caub this is a duplicate of https://github.com/ljharb/jellobot/issues/8; issues don't go on this repo anymore.

**Comment by caub** [comment]
Oh I didn''t notice, this is always annoying
